all: 
    n: 1
    time: 00:10:00
    pmem: 2000mb
split:
    n: 4
    time: 00:30:00
    pmem: 10g
fastqc_raw:
    n: 1
    time: 0-3:00:00
    pmem: 4000mb
trimmomatic: 
    n: 1
    time: 02:00:00
    pmem: 4000mb
cutadapt:
    n: 1 
    time: 0-12:00:00
    pmem: 4000mb
fastqc_trimmed:
    n: 1
    time: 0-1:00:00
    pmem: 4000mb
bwa_map:
    n: 8
    time: 0-6:00:00
    pmem: 32g
sam_to_sorted_bam:
    n: 1
    time: 0-1:00:00
    pmem: 20000mb
merge_bam:
    n: 1
    time: 0-3:00:00
    pmem: 4000mb
mark_duplicates:
    n: 1
    time: 0-12:00:00
    pmem: 80000mb
agg_and_dedup:
    n: 1
    time: 0-03:00:00
    pmem: 20000mb
build_bai:
    n: 1
    time: 0-3:00:00
    pmem: 8000mb

reheader:
    n: 1
    time: 0-3:00:00
    pmem: 4000mb
bam_stats:
    n: 1
    time: 0-3:00:00
    pmem: 4000mb
counts1_for_BQSR:
    n: 32
    time: 0-4:00:00
    pmem: 125000m
counts2_for_BQSR:
    n: 32
    time: 0-4:00:00
    pmem: 125g
analyze_covariates:
    n: 1
    time: 0-1:00:00
    pmem: 8000mb
base_recal:
    n: 32
    time: 0-5:00:00
    pmem: 125g
rename_bam:
    n: 1
    time: 0-3:00:00
    pmem: 8000mb
depth_of_coverage:
    n: 32
    time: 0-3:00:00
    pmem: 125g
    
haplotype_caller_contigs:
    n: 4
    time: 0-1:00:00
    pmem: 8000mb
merge_gvcf_contigs:
    n: 1
    time: 0-1:00:00
    pmem: 8000mb
haplotype_caller_chrs:
    n: 4
    time: 0-6:00:00
    pmem: 8000mb
validate_vcf:
    n: 30
    time: 0-1:00:00
    pmem: 30000mb
genotype_chrs:
    n: 30
    time: 0-1:00:00
    pmem: 100000mb
genotype_contigs:
    n: 30
    time: 0-3:00:00
    pmem: 300000mb
extract_snps_chrs:
    n: 1
    time: 0-1:00:00
    pmem: 8000mb
extract_snps_contigs:
    n: 1
    time: 0-1:00:00
    pmem: 8000mb
filter_snps_chrs:
    n: 1
    time: 0-1:00:00
    pmem: 8000mb
filter_snps_contigs:
    n: 1
    time: 0-1:00:00
    pmem: 8000mb
cat_snps:
    n: 1
    time: 0-1:00:00
    pmem: 8000mb
extract_indels_chrs:
    n: 1
    time: 0-1:00:00
    pmem: 8000mb
extract_indels_contigs:
    n: 1
    time: 0-1:00:00
    pmem: 8000mb
filter_indels_chrs:
    n: 1
    time: 0-1:00:00
    pmem: 8000mb
filter_indels_contigs:
    n: 1
    time: 0-1:00:00
    pmem: 8000mb
cat_indels:
    n: 1
    time: 0-1:00:00
    pmem: 8000mb